/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.midea.VadAsr;

public class PocketSphinxJNI {
  public final static native boolean EnvEnergy(short[] jarg1);
  public final static native String VoiceDetect(short[] jarg1, long jarg2, Config jarg2_);
}
